### PR TITLE
MANIFEST.in is required to have the resources installed correctly

### PR DESCRIPTION
**Pull request by ochriste**
cf http://python-packaging.readthedocs.io/en/latest/non-code-files.html

### CODE REVIEW

**Comment by agronholm** [comment]
I'm no longer interested in maintaining this. Would you like to become the maintainer?

**Comment by ochriste** [comment]
@agronholm "this" being js.jqgrid, js.jqueryui_selectmenu, js.jqueryui_syronex_colorpicker and js.jquery_markitup ?

**Comment by agronholm** [comment]
Only js.jqgrid.

**Comment by do3cc** [comment]
@ochriste This repo is not being maintained any longer. The last change was from 4 years ago and the js library is probably terribly out of date.
I see that you forked it and I see that this package does not get pulled a lot from anybody. 
So instead I will just delete this repository, then your repo becomes the master.
If you are interested in maintaining this package, feel free to tell me your pypi username and I add you.

**Pull request closed without merging**
